### ISSUE TITLE
How to include this in Platformio ?

### ISSUE THREAD

**Issue by glucee** [stickbreaker/arduino-esp32#16]
Please fill the info fields, it helps to get you faster support ;)

If you have a Guru Meditation Error, please decode it:
https://github.com/me-no-dev/EspExceptionDecoder

----------------------------- Remove above -----------------------------

### Hardware:
Board:							ESP32 Dev Module?
Core Installation/update date:	       11/Dec/2017
IDE name:						Platform.io
Flash Frequency:					40Mhz
Upload Speed:					9600

### Description:
How to easily include this one in the platformio ?

**Comment by stickbreaker** [comment]
I have no experience with platformio. This is a fork of arduino-esp32. So, whatever procedures are used to use espressif/arduino-esp32 will work with this fork.  

If you use the `Wire()` library there should not be any differences.

Chuck.

**Comment by beegee-tokyo** [comment]
@stickbreaker 
the usual steps would be to put the platform path into platformio.ini of the project.
**`platform = https://github.com/stickbreaker/arduino-esp32.git`**
But unfortunately that fails with some weird error messages. Maybe because your repo is a fork. Don't really know why.
@glucee 
**_2 possible solutions:_**
**a) just replace** 
**`C:\Users\beegee\.platformio\packages\framework-arduinoespressif32\cores\esp32\esp32-hal-i2c.c`**
**`C:\Users\beegee\.platformio\packages\framework-arduinoespressif32\cores\esp32\esp32-hal-i2c.h`**
**`C:\Users\beegee\.platformio\packages\framework-arduinoespressif32\cores\esp32\esp32-hal-log.h`**
**`C:\Users\beegee\.platformio\packages\framework-arduinoespressif32\libraries\Wire\src\Wire.cpp`**
**`C:\Users\beegee\.platformio\packages\framework-arduinoespressif32\libraries\Wire\src\Wire.h`**
with the same files from stickbreakers repo.
**b) use git to clone stickbreakers repo**
rename 
**`C:\Users\beegee\.platformio\packages\framework-arduinoespressif32`**
to 
**`C:\Users\beegee\.platformio\packages\framework-arduinoespressif32.org`**
clone stickbreakers repo into an empty 
**`C:\Users\beegee\.platformio\packages\framework-arduinoespressif32`**
then clean your project, recompile and you are using this repo.

**Comment by stickbreaker** [comment]
@beegee-tokyo Thanks for the help! 👍 

Chuck.

**Comment by echoGee** [comment]
Some files that are in the standard repo are not present in stickbreakers' repo. So another solution is to copy stickbreakers files and overwrite all the files in C:\Users\beegee\.platformio\packages\framework-arduinoespressif32 folder. This keeps all the extra files as is.

**Comment by beegee-tokyo** [comment]
@eohan, don't do that. You might mess up other things. Just grab the following files from stickbreakers repo 
```
\libraries\Wire\scr\Wire.h
\libraries\Wire\scr\Wire.cpp
\cores\esp32\esp32-hal-i2c.h
\cores\esp32\esp32-hal-i2c.c
\cores\esp32\esp32-hal-log.h
```
and overwrite the according files in your **`framework-arduinoespressif32`** folder.
